version: '3'

services:
  app:
    user: root
    build:
      context: ""
      dockerfile: Dockerfile
    image: web_server
    ports:
      - 8000:8000
    depends_on:
      migration:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    command: bash -c "uvicorn crud:app --host 0.0.0.0 --port 8000"

  migration:
    image: web_server
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "alembic upgrade head"

  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: '1234'
      POSTGRES_NAME: 'postgres'
      POSTGRES_USER: 'postgres'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5