version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: '1234'
      POSTGRES_NAME: 'postgres'
      POSTGRES_USER: 'postgres'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      myApp-network:
        aliases:
          - postgresForMyApp

  app:
    build: .
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - myApp-network
    command: bash -c "alembic upgrade head && uvicorn crud:app --host 0.0.0.0 --port 8000"

networks:
  myApp-network:
    driver: bridge
