"""Add date_created to post

Revision ID: a8cc65989d34
Revises: 9b2af4d98f77
Create Date: 2022-06-16 19:07:42.587339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8cc65989d34'
down_revision = '9b2af4d98f77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'date_created')
    # ### end Alembic commands ###
